services:
#    _defaults:
#        autowire: true
#        autoconfigure: true

    SensioLabs\Security\SecurityChecker:
        public: false

    SensioLabs\Security\Command\SecurityCheckerCommand:
        arguments: ['@SensioLabs\Security\SecurityChecker']
        tags:
            - { name: console.command }
